@extends('main')

@section('title','| story')

@section('content')
	<div class="row">
		<div class="col-md-10">
			<div class="cow_design top-spacing offset-2">
				{{-- @foreach($cowreply as $reply)
						<p style="padding: 10px; color:white; background-color:black; border-style:solid 1px black; border-radius:5px;"><span style="font-size:0.6rem; color:yellow;">{{$reply->created_at}}</span> &nbsp;{{ $reply->body }}</p>
				@endforeach --}}
				<p style="padding: 10px; color:white; background-color: black; border-radius:5px;">sorry, actually I was working on this website so it was in error.. so now If you see this page please let me know with mail..and now I have updated option where I can reply from any where..so please search as "http://159.89.169.152/blog/cow-talk".. you will see a page where you can make comment and I as well..so after seeing this page please confirm me once with mail option.. then you can ask your question in cow-talk option I will reply you dear..</p>
				<hr>
				{{-- <p style="padding: 10px; color:white; background-color: black; border-radius:5px;"> sorry cow, I could not reply your question now, because until I have laptop in my hand It could not be possible to update msg for you, yesterday late night night I was working on chat option but still I could not make it some error was still there..So, I will reply you tomorrow dear.. I hope today night I can make it.. so tomorrow morning I will reply you.. so you will have chat option there I can reply.. sorry dear cow..stay smile.. ;-)</p>
				<hr>
				<p style="padding: 10px; color:white; background-color: black; border-radius:5px;">I respect your feelings and emotions dear, I never pushed you for anything. so, always come up with strong reason what makes u to do furhter things or taking steps. whatever you do, never leave things to regret. take ur time as much as u want, I will wait. I'm not trying to manipulate your mind dear towards me.. but it's fact..If you could not open up with your sis also for your feelings then sorry dear things will not be in ur hand.. because, there will be some certain point where we sould take our chance and open up with all words what we kept on hiding in heart. If we still could not do, means we are lying with ourselve not with others..cow, dear I always told you please appear emotionally bold if you have any words to say with someone..so, believe yourself..and dont forget to delete history before leaving from the PC where you sitting..because it is not authenticated yet..today till evening I will make this page as authenticated page, so, if you login with ur user id and password then only it will get open..so please take care of it..I will make chat option today..so, I will update you here only in next msg how can you reply in chat option..</p>
				<hr>
				<p style="padding: 10px; color:white; background-color: black; border-radius:5px;">Okay dear, do one thing, don't make your life so complicated..you said them "you are not talking with me." I know you must be giving time yourself, right..so, no issue..even you are not talking with me. but make sure that you are not raising their hope not for bhutni as well that you are coming back to his life..and most imp thing, at certain point If you thing that you should go with him, and you are done with this running life..please never forget to tell me without any hasitaion, because I always gave you a comfort zone where you can share with me every matter whether it is physical or emotional so why not this, because I give importance to you more than others..so, never ever think what monkey would think for ur decisions, I would be happy if you are happy..the moment you make any dicision, please stick on that and update me any how..</p>
				<hr>
				<p style="padding: 10px; color:white; background-color: black; border-radius:5px;">sorry dear, actually I went to bathroom, so that's y I could not see your msg.. so, now you reply me.. I will reply back to you.. and why you got angry mis??</p>
				<hr>
				<p style="padding: 10px; color:white; background-color: black; border-radius:5px;">I got your mail dear, and that "bye miss you" I have written for that specific day only, not permanently. here miss you mean is I missing those moments which I used to have not I m saying to you forever stupid, silly, duffer, dimag se paidal. I'm getting your all the mail.. whenever you mail me.. I will reply here only so refresh the page after some time you get reply..okay</p>
				<hr>
				<p> --}}
					{{-- <h4>Hii Cow, </h4><br>
				<p>I know dear, how you been going through this bi-directional feelings where you are not able to find a clue to make your path one directional..that's obvious dear. so, no comments on this because, that I can see in your eyes and always sees a hope.<i class="fas fa-smile"></i><br>
				<p>Anyway, It's been long time expressing my feelings. So,again I came back with flood of my feelings so try to bear with me dear..hope you will read it completely..</p>
				Here, the matter of fact you can't deny at all that I alway feel smile whenever I see you but not as common as like	a baby feels happy after seeling bucket of toys rather, until I see myself in your eyes and could find monkey not prakash..
				So, please think once dear, how would I suppose to manage the moment where you just turn your face and try to keep your eyes away from me..I tried multiple times to see you but it could not happen. It made me feel so guilty that how a person can try to get rid of me like that who I know the level of my best, I was clueless and started thinking, did I do any shameless things that would not be acceptable at all.</p>
				<p>I don't know what exactly the conversation was happened among you guys after that chat where bhutni was replying me..then next morning moment got changed, I reached office before you guys because, I came by auto, while coming I saw you guys were again having a big conversation walking on padistrian way of the bridge. After reaching office bhutni came to me and said "prakash I want to talk to you". I said "Ok dear". Afternoon, you guys went early because, the sale event was going on and I had to come later, I called bhutni because, bhaji asked me to convey the msg to eat the sambhar early so that it will not get stale till night, in the same call I asked her to come early in evening shift so that we will talk on this..but she did not come, I was waiting in office in entire break shift..then while going time she came to me to call me for cab..but I was doing something in PC with Jibin.. I said dear, check my name is there or not in cab list and update me..she said "I'm not going to update you". and the same night I got message stating "Prakash I have given 5000 to swamy take it and rest of the money I will give you in next month". Instently, I replied her back "Why it was required dear, I know you guys have to manage with it dear, same night I got my salary as well and updated her too." but she did not reply..later I messaged her again in whatsapp she did not reply. I thought she want to get rid of me and I felt I'm no prakash any more whom she knows. Next day again she gave strange reaction like just few hours ago we met. </p>
				<p>I'm sorry cow, I behaved weired on that day where you tried to keep away your eyes. for that, I came out with words next day and said "Why did you try to avoid your eyes from me, did I do shameless deed". even after remebering the words you said "If I don't see you or don't talk to you, please don't do with me". I never forget this words dear that's why I never complained, why you are not talking with me and never asked you to try to find a way to talk with me ..becuase this god damn boy fell for you and want to talk with you every day.</p>
				<p>your question : <h4>Can I live without you or not?</h4></p>
				<p>Dear cow, I ever said to you that I hate die word, then how can I kill myself. I never believe in reincarnation or rebirth because, we got this one life and one chance to make ourself whatever we want to be, we live with dreams which we ever want to come true. never ever try to convince yourself with false truth which never exist. Cow, I'm not so expressive to express my love with words but you may feel love with me in every second the moment you spend with me. I will try my best to make you my life If you just step up with hope and keep your faith alive. we are the creater of our problems then why we scare to fix this. Dear, I can be stupid in love but not for my life. this life has so much mean beside dieing in love, even I hate those people, who talk about die and commit to suicide that you already know. If you will not become part of my life, I can hurt myself until I feel that this is over and this god damn things will never let me be myself, that is common tendency of every people that they do if they don't get what they love. I can do so might be but naturally if I feel sad ..but, sooner or later I would done with this. I always keep things safe which I love a lot, and I respect those people emotion and opinions who closed to me. then, you are neither thing nor you come in those people, you are the one whom I love. whom I can shower unconditional love. I hope, you can see my love towards in my eyes. I can love you till the end of my breath but sorry dear I can't die, that I have learnt from my life so far, because this is never been a solution to run from situation and not admiting the consequences. let your life live, get up and take a deep breath.</p>
				<p>Dear cow, I know you tired of doing chat hidely and listening scolding words. I will be there for you, never think that I'm leaving you alone in your situation. before going from here I will make sure thing will go on easy.</p>
				<p>And I'm really sorry, that I could not update you that I'm leaving this place by this month 21st of 25th. I have already put the paper. So, take your time and be normal dear, I will wait for your reply, Just update me once wherever you make you decision. Never think about what I would be there, I will be waiting for your positive reply, so, make sure you are specific in your decision. that will make me happy for you. I always want to make you happy that's it. so, be sure you are happy for your decision. and yes, papa visited hospital again for his knee pain and papa might undergo knee sergery again that you already know. I have told this reason why I want to go native parmanently, I will go native but not for permanently, I will be in hyderabad once my father will feel batter, but the main reason you know why I am leaving this company(remeber 29th april).</p>
				<p>make sure you have removed the history from your mobile after reading this. otherwise, you will be in trouble, that I never want. I hope I could find a way to talk with you before leaving this place. If you have any words to say with me then you can click on contact me and you can write your words and you can send mail but never forget to attach you one pic, even that is manadetory.</p>
				<p>Be normal, don't worry I will not put you in trouble ever. take your time and be smiley always.</p>
				<p>If you could remeber this link then please, try to remember, I will update content for you, or if you need any reply..just mail me, I will reply here in the same link.. thanks </p>
				<p>Bye cow, miss you dear <i class="fas fa-smile"></i></p>
				</p> --}}
			</div>
		</div>
	</div>
@endsection

